# Generated by Django 4.2.7 on 2023-11-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="joinedDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="mobileNumber",
            field=models.IntegerField(null=True),
        ),
    ]
