# Generated by Django 4.2.7 on 2023-12-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_joineddate_member_mobilenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentName", models.CharField(max_length=255)),
                ("studentAge", models.IntegerField(null=True)),
                ("studentEducation", models.CharField(max_length=255)),
            ],
        ),
    ]
